apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: k3opsot9m-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/k3opsot9m-java-quarkus-gitops